language: php
sudo: false
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
install:
  - travis_retry composer update
script:
  - vendor/bin/phpunit tests/ --bootstrap=tests/bootstrap.php --config=tests/phpunit.xml
